2024-09-10 17:07:08,669 INFO    StreamThr :527509 [internal.py:wandb_internal():85] W&B internal server running at pid: 527509, started at: 2024-09-10 17:07:08.668840
2024-09-10 17:07:08,670 DEBUG   HandlerThread:527509 [handler.py:handle_request():158] handle_request: status
2024-09-10 17:07:08,672 INFO    WriterThread:527509 [datastore.py:open_for_write():87] open: /home/ubuntu/frontend/bistro/wandb/run-20240910_170708-Miner-5EkVG/run-Miner-5EkVG.wandb
2024-09-10 17:07:08,672 DEBUG   SenderThread:527509 [sender.py:send():391] send: header
2024-09-10 17:07:08,673 DEBUG   SenderThread:527509 [sender.py:send():391] send: run
2024-09-10 17:07:08,676 INFO    SenderThread:527509 [sender.py:_setup_resume():761] checking resume status for None/bistro/Miner-5EkVG
2024-09-10 17:07:08,810 ERROR   SenderThread:527509 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:07:08,810 ERROR   SenderThread:527509 [internal_api.py:execute():350] {"errors":[{"message":"run Miner-5EkVG was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:07:10,051 ERROR   SenderThread:527509 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:07:10,051 ERROR   SenderThread:527509 [internal_api.py:execute():350] {"errors":[{"message":"run Miner-5EkVG was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:07:12,325 ERROR   SenderThread:527509 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:07:12,325 ERROR   SenderThread:527509 [internal_api.py:execute():350] {"errors":[{"message":"run Miner-5EkVG was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:07:12,325 INFO    SenderThread:527509 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 345, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2024-09-10 17:07:13,674 DEBUG   HandlerThread:527509 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:07:17,228 ERROR   SenderThread:527509 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:07:17,229 ERROR   SenderThread:527509 [internal_api.py:execute():350] {"errors":[{"message":"run Miner-5EkVG was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:07:18,676 DEBUG   HandlerThread:527509 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:07:23,678 DEBUG   HandlerThread:527509 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:07:25,934 ERROR   SenderThread:527509 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:07:25,934 ERROR   SenderThread:527509 [internal_api.py:execute():350] {"errors":[{"message":"run Miner-5EkVG was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:07:28,680 DEBUG   HandlerThread:527509 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:07:33,681 DEBUG   HandlerThread:527509 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:07:38,683 DEBUG   HandlerThread:527509 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:07:42,119 ERROR   SenderThread:527509 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:07:42,119 ERROR   SenderThread:527509 [internal_api.py:execute():350] {"errors":[{"message":"run Miner-5EkVG was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:07:43,684 DEBUG   HandlerThread:527509 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:07:48,686 DEBUG   HandlerThread:527509 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:07:53,687 DEBUG   HandlerThread:527509 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:07:58,689 DEBUG   HandlerThread:527509 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:08:03,691 DEBUG   HandlerThread:527509 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:08:08,692 DEBUG   HandlerThread:527509 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:08:13,694 DEBUG   HandlerThread:527509 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:08:18,696 DEBUG   HandlerThread:527509 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:08:19,879 ERROR   SenderThread:527509 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:08:19,879 ERROR   SenderThread:527509 [internal_api.py:execute():350] {"errors":[{"message":"run Miner-5EkVG was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:08:23,698 DEBUG   HandlerThread:527509 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:08:28,699 DEBUG   HandlerThread:527509 [handler.py:handle_request():158] handle_request: keepalive
