2024-09-10 17:07:08,716 INFO    StreamThr :527514 [internal.py:wandb_internal():85] W&B internal server running at pid: 527514, started at: 2024-09-10 17:07:08.715611
2024-09-10 17:07:08,718 DEBUG   HandlerThread:527514 [handler.py:handle_request():158] handle_request: status
2024-09-10 17:07:08,718 INFO    WriterThread:527514 [datastore.py:open_for_write():87] open: /home/ubuntu/frontend/bistro/wandb/run-20240910_170708-Miner-5DHYe/run-Miner-5DHYe.wandb
2024-09-10 17:07:08,719 DEBUG   SenderThread:527514 [sender.py:send():391] send: header
2024-09-10 17:07:08,722 DEBUG   SenderThread:527514 [sender.py:send():391] send: run
2024-09-10 17:07:08,725 INFO    SenderThread:527514 [sender.py:_setup_resume():761] checking resume status for None/bistro/Miner-5DHYe
2024-09-10 17:07:08,884 ERROR   SenderThread:527514 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:07:08,884 ERROR   SenderThread:527514 [internal_api.py:execute():350] {"errors":[{"message":"run Miner-5DHYe was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:07:10,051 ERROR   SenderThread:527514 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:07:10,052 ERROR   SenderThread:527514 [internal_api.py:execute():350] {"errors":[{"message":"run Miner-5DHYe was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:07:12,123 ERROR   SenderThread:527514 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:07:12,123 ERROR   SenderThread:527514 [internal_api.py:execute():350] {"errors":[{"message":"run Miner-5DHYe was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:07:12,123 INFO    SenderThread:527514 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 345, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2024-09-10 17:07:13,723 DEBUG   HandlerThread:527514 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:07:16,260 ERROR   SenderThread:527514 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:07:16,260 ERROR   SenderThread:527514 [internal_api.py:execute():350] {"errors":[{"message":"run Miner-5DHYe was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:07:18,725 DEBUG   HandlerThread:527514 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:07:23,726 DEBUG   HandlerThread:527514 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:07:25,715 ERROR   SenderThread:527514 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:07:25,715 ERROR   SenderThread:527514 [internal_api.py:execute():350] {"errors":[{"message":"run Miner-5DHYe was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:07:28,728 DEBUG   HandlerThread:527514 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:07:33,730 DEBUG   HandlerThread:527514 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:07:38,731 DEBUG   HandlerThread:527514 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:07:43,733 DEBUG   HandlerThread:527514 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:07:45,377 ERROR   SenderThread:527514 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:07:45,377 ERROR   SenderThread:527514 [internal_api.py:execute():350] {"errors":[{"message":"run Miner-5DHYe was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:07:48,734 DEBUG   HandlerThread:527514 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:07:53,736 DEBUG   HandlerThread:527514 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:07:58,737 DEBUG   HandlerThread:527514 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:08:03,739 DEBUG   HandlerThread:527514 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:08:08,740 DEBUG   HandlerThread:527514 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:08:13,742 DEBUG   HandlerThread:527514 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:08:18,743 DEBUG   HandlerThread:527514 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:08:23,745 DEBUG   HandlerThread:527514 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:08:24,429 ERROR   SenderThread:527514 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:08:24,429 ERROR   SenderThread:527514 [internal_api.py:execute():350] {"errors":[{"message":"run Miner-5DHYe was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:08:28,746 DEBUG   HandlerThread:527514 [handler.py:handle_request():158] handle_request: keepalive
