2024-09-10 17:07:09,060 INFO    StreamThr :527801 [internal.py:wandb_internal():85] W&B internal server running at pid: 527801, started at: 2024-09-10 17:07:09.060332
2024-09-10 17:07:09,062 DEBUG   HandlerThread:527801 [handler.py:handle_request():158] handle_request: status
2024-09-10 17:07:09,063 INFO    WriterThread:527801 [datastore.py:open_for_write():87] open: /home/ubuntu/frontend/bistro/wandb/run-20240910_170709-Miner-5D2uD/run-Miner-5D2uD.wandb
2024-09-10 17:07:09,064 DEBUG   SenderThread:527801 [sender.py:send():391] send: header
2024-09-10 17:07:09,065 DEBUG   SenderThread:527801 [sender.py:send():391] send: run
2024-09-10 17:07:09,068 INFO    SenderThread:527801 [sender.py:_setup_resume():761] checking resume status for None/bistro/Miner-5D2uD
2024-09-10 17:07:09,287 ERROR   SenderThread:527801 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:07:09,288 ERROR   SenderThread:527801 [internal_api.py:execute():350] {"errors":[{"message":"run Miner-5D2uD was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:07:10,524 ERROR   SenderThread:527801 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:07:10,524 ERROR   SenderThread:527801 [internal_api.py:execute():350] {"errors":[{"message":"run Miner-5D2uD was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:07:12,603 ERROR   SenderThread:527801 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:07:12,603 ERROR   SenderThread:527801 [internal_api.py:execute():350] {"errors":[{"message":"run Miner-5D2uD was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:07:12,603 INFO    SenderThread:527801 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 345, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2024-09-10 17:07:14,066 DEBUG   HandlerThread:527801 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:07:17,461 ERROR   SenderThread:527801 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:07:17,462 ERROR   SenderThread:527801 [internal_api.py:execute():350] {"errors":[{"message":"run Miner-5D2uD was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:07:19,068 DEBUG   HandlerThread:527801 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:07:24,070 DEBUG   HandlerThread:527801 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:07:27,176 ERROR   SenderThread:527801 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:07:27,176 ERROR   SenderThread:527801 [internal_api.py:execute():350] {"errors":[{"message":"run Miner-5D2uD was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:07:29,071 DEBUG   HandlerThread:527801 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:07:34,072 DEBUG   HandlerThread:527801 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:07:39,074 DEBUG   HandlerThread:527801 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:07:44,075 DEBUG   HandlerThread:527801 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:07:45,502 ERROR   SenderThread:527801 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:07:45,502 ERROR   SenderThread:527801 [internal_api.py:execute():350] {"errors":[{"message":"run Miner-5D2uD was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:07:49,077 DEBUG   HandlerThread:527801 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:07:54,078 DEBUG   HandlerThread:527801 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:07:59,080 DEBUG   HandlerThread:527801 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:08:04,081 DEBUG   HandlerThread:527801 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:08:09,083 DEBUG   HandlerThread:527801 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:08:14,084 DEBUG   HandlerThread:527801 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:08:19,086 DEBUG   HandlerThread:527801 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:08:20,748 ERROR   SenderThread:527801 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:08:20,748 ERROR   SenderThread:527801 [internal_api.py:execute():350] {"errors":[{"message":"run Miner-5D2uD was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:08:24,087 DEBUG   HandlerThread:527801 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:08:29,089 DEBUG   HandlerThread:527801 [handler.py:handle_request():158] handle_request: keepalive
